const onAddFn = () => console.log("onAdd test");
const items = [
    {
        title: "Bicicleta Aro 29",
        image: "fenixaro29.jpg",
        detail: "Bicicleta MTB, perfecta para salidas a la montaña",
        id: 1,
        categoryId: 1,
        price: 22000,
        initial: 3,
        stock: 6,
        onAdd: onAddFn,
    },
    {
        title: "Moto Yamaha",
        image: "yamahamoto.jpg",
        detail: "Moto Yamaha para ciudad",
        id: 2,
        categoryId: 2,
        price: 522000,
        initial: 2,
        stock: 5,
        onAdd: onAddFn,
    },
    {
        title: "Auto BMW Ces2018",
        image: "bmwces2018auto.jpg",
        detail: "Auto BMW, modelo para ciudad y carretera",
        id: 3,
        categoryId: 3,
        price: 692000,
        initial: 0,
        stock: 2,
        onAdd: onAddFn,
    },
    {
        title: "Suzuki Celerio",
        image: "suzukicelario.jpg",
        detail: "Suzuki Celerio 1.0 Glx usado",
        id: 4,
        categoryId: 3,
        price: 392000,
        initial: 0,
        stock: 0,
        onAdd: onAddFn,
    },
    {
        title: "Moto Yamaha Fz 250 2022",
        image: "motoyamahafz.jpg",
        detail: "Yamaha Fz 250 2022 usada",
        id: 5,
        categoryId: 2,
        price: 421000,
        initial: 0,
        stock: 2,
        onAdd: onAddFn,
    },
    {
        title: "Bicicleta Bahner 24",
        image: "bahner24.jpg",
        detail: "Bicicleta MTB",
        id: 6,
        categoryId: 1,
        price: 52000,
        initial: 0,
        stock: 1,
        onAdd: onAddFn,
    },
];

export { items };
